### PR TITLE
Add disclaimer to staging app

### LINKED ISSUE #293: Disclaimer for staging environment
If someone by chance stumbles over the where2help staging environment at heroku they might think it's production and sign up with real, confidential data there.

We could add a flashy disclaimer to the top of every page to make this clear `unless Rails.env.production?`

### PR DESCRIPTION
**Pull request by mftaff**
closes #293 

I added a before_action to application controller that adds a flash message if the app is not in production.

I am more than happy to make any changes required - I am newish to open source contributing.

😄

### CODE REVIEW

**Comment by groe** [comment]
Thank you very much for contributing, @mftaff – appreciate it!

* Wording: I would prefer something like "This is a TEST VERSION of Where2help. Do NOT enter any personal or confidential data." because (a) the term "test" is less tech-y (esp. in german) and (b) to strongly discourage any real data, not just warn about it.

* Having this in the `flash` could collide with other things that go into it. What do you think about some specific HTML markup with `<% unless Rails.env.production? %>` tags in the layout files instead?

**Comment by mftaff** [comment]
😄 good points, I will make the changes now.

English: This is a TEST VERSION of Where2help. Do NOT enter any personal or confidential data.
German: Dies ist eine Testversion von Where2help. Geben Sie keine persönlichen oder vertraulichen Daten ein.

Is that a good translation? I don't speak german, I just used Google Translate.

**Comment by mftaff** [comment]
Awesome I made the changes. I tried to copy the style that was used for the `flash_messages` helper.
😄

**Comment by groe** [comment]
Sorry for the delay, @mftaff 

The disclaimer message appears twice now. I think that's because of the `concat`, but I think you can just remove it?

Minor suggestions:

* You could rename `display_disclaimer` to `environment_disclaimer` to make it more descriptive
* Same for `application.disclaimer`
* By adding the `alert` class instead of the `disclaimer` class it would look the same as regular alerts. Right now it doesn't (lacks padding, border, etc.)

**Comment by mftaff** [comment]
👍 how's it look now?

**Comment by groe** [comment]
Perfect, merged and [deployed to staging](http://where2help.herokuapp.com)! Thanks @mftaff

**Pull request merged**
