### PR TITLE
Add MapBox.js map for each individual need's view

### PR DESCRIPTION
**Pull request by ramonh**
This addresses #14 by adding a little map with a marker for each need.

Please note that you'll need to rerun the `db:populate` task for the premade needs to have lattitudes and longitudes, which the map needs

### CODE REVIEW

**Comment by klappradla** [comment]
Why did u decide against [https://github.com/aai/mapbox-rails](the gem)? I'd suggest this performance-wise over the CDN version.

**Comment by ramonh** [comment]
I was running into an error similar to this: https://github.com/aai/mapbox-rails/issues/15

**Comment by haslinger** [comment]
Are you aware of https://www.mapbox.com/pricing/ ?

**Comment by ramonh** [comment]
I wasn't, no, thank you. I'll close this and rework it.

**Pull request closed without merging**
