### PR TITLE
Remove default mailer from-addresses

### LINKED ISSUE #205: Wrong domain in mailer "from" address and canonical tags
The following files contain "where2help.at" instead of "where2help.wien" at some place:

* app/mailers/admin_mailer.rb (from-address)
* app/mailers/ngo_mailer.rb (from-address)
* app/mailers/user_mailer.rb (from-address)
* public/404.html (canonical tag)
* public/422.html (canonical tag)
* public/500.html (canonical tag)

My suggestion would be to centralize the from-address setting in an initializer. And regarding the canonical tag: What's the purpose of it on an error page?

### PR DESCRIPTION
**Pull request by groe**
Fixes #205

### CODE REVIEW

**Comment by klappradla** [comment]
Fixed the specs and removed the canonical tags from the static pages *(don't know why we have them...)*

**Comment by haslinger** [comment]
They were there, because they are there in Rails's standard templates, and they are in Rails for SEO reasons.

**Comment by klappradla** [comment]
Ah ok, @haslinger, I just looked at [the original file]( https://github.com/where2help/where2help/blob/19e50d3ea15c46247a50e6419f7006fecb34bf0b/public/500.html) and since it didn't have them, I thought we could get rid of them.

Do you think they should be back in? I was just wondering how to do them env-independent, since we're not really hitting the app server here...

**Comment by haslinger** [comment]
No need to put them back in because error pages are not SEO relevant.

**Pull request merged**
