### PR TITLE
Update active_record.de.yml

### PR DESCRIPTION
**Pull request by votexx**
menu changed to eliminate the word "event": 
Event -> Einsatz
Einsatz -> Mein Einsatz

### CODE REVIEW

**Comment by haslinger** [comment]
To name events as well as shifts "Einsätze" in German will cause major confusion!

**Comment by votexx** [comment]
yes, you´re right - I´ll think about it and possible work-around (also if that means, to change nothing)

**Comment by klappradla** [comment]
Besides causing major confusion, **"Mein Einsatz"** for *shift* can't work, since it would be named like this for **EVERYONE**, meaning also NGOs creating events with shifts and non-opted in users browsing events.

**Comment by votexx** [comment]
Sorry...didn´t get that this also applies for the NGO-view. I think we can discard this change.

**Comment by votexx** [comment]
suggestion:
Event -> Einsätze (besides when creating an event it´s already named "Einsatz")
Shifts -> Termine (Deine/Meine Termine)

@klappradla, now that I´m looking at the NGO-view, I don´t get what you mean - there is no "Einsatz/shift"-menu for NGOs as you cannot attend shifts as an NGO.

**Comment by klappradla** [comment]
It's not just translating the menu items, it's translating the name of the entity within the whole application - that's why it'd also affect the NGO parts.

**Comment by votexx** [comment]
So the entity thing is more of a coding problem - I guess that´s why I don´t get it. If the entity thing causes major problems, I guess its´not worth the effort.

For the purpose of menu and names: Event still sounds more like "a fun thing to do" and therefore in my opinion the term "Einsatz" would be more suitable. As for the NGO: they´ll never actually see both names at the same time as there is "creating the event" (=Einsatz) and subsequently adding the shifts (="Termine" within the "Einsatz").

**Comment by klappradla** [comment]
Ok, I get your point. However, I think for now it's best to just stay consistent with the naming. We'll see if it's a problem or not after all.

**Comment by votexx** [comment]
OK, if we can just keep in mind "Einsatz" und "Termine" for the future and give it a second thought later on.

**Pull request closed without merging**
