### PR TITLE
Fix indentation

### PR DESCRIPTION
**Pull request by groe**
Any opinions on [rubocop](https://github.com/bbatsov/rubocop) to maintain a consistent code style?

### CODE REVIEW

**Comment by klappradla** [comment]
I already thought about giving it a try. What slightly got me off this idea again though was: depending on how strong these rules are enforced, I thought it could higher the barriers for new people in the project and kinda *"kill"* the spirit of a community project originated in a hackathon where everyone, especially newcomers can jump in to help, give their opinions, etc. as long as they just care enough.

Still, on the long term it would probably facilitate having people of different experience levels and backgrounds working on the same codebase. And I'm kinda interested in it personally 🙈 

I'd put this up for discussion then...

**Comment by groe** [comment]
@klappradla Sorry, I opened up a separate issue #159 for the rubocop suggestion after realizing this is probably a merge-and-forget PR. Feel free to close one of the issues or repost your comment to keep the discussion in one place.

**Comment by haslinger** [comment]
Will at least put some delay on the project as somebody has to define a style, create a style guide and create consistency of the current code base. Then all others have to catch up and adopt to the agreed code style.
I don't believe it's worth it, but I'm not opposed to it as long as nobody complains about the delays introduced.

**Comment by klappradla** [comment]
*(so discussion here after all 😉 )*

**Comment by groe** [comment]
IMO rubocop would be beneficial but this has low priority.

+ Setting up rubocop is as easy as adding it to the Gemfile and adding a `.rubucop.yml` file. Extra points for CI config.
+ There may be lots of warnings in the beginning but fixing them is usually a beginner-friendly task with instant gratification :)

**Pull request merged**
