### PR TITLE
Map scrolling on events page fix 203

### PR DESCRIPTION
**Pull request by Thrillberg**

### CODE REVIEW

**Comment by klappradla** [comment]
Hey @Thrillberg thanx for this one 🎉 

Unfortunately it does not solve our main painpoint: scrolling on mobile devices 🙈 

For the desktop, I'd say just disabling mouse scrolling for zoom should be fine - I guess the `+`, `-`signs should be fine here as they seem to be the main interaction points for people when they want to zoom in or out.

I played around with various options from [the docs](http://leafletjs.com/reference-1.0.0.html), but nothing really worked well on e.g. my iPhone. Disabling any scrolling or tapping options usually leads to the page itself no longer being scrollable on touch devices... 

So I'll merge this PR, but probably then get rid of scroll-zoom all together. Hope that's fine for you. Again, thanx a ton for your time and work on this!

**Comment by Thrillberg** [comment]
Hi @klappradla, thanks for merging this in. Didn't realize that it still isn't right for mobile devices. Sorry about that!

**Comment by haslinger** [comment]
I gave this another try with 5fd9980 .
No dragging is disabled as no mouseover is triggered.
* (on desktops) mouse draggings are fine because mouseover enables dragging
* (on mobile) single finger drag is disabled and no unintentional draggings are happening.
* (on mobile) double finger drag is working and not disturbing, because most people scroll pages with one finger.
What do you think?
@klappradla master / this commint is not merged into fsw yet.

**Comment by klappradla** [comment]
Haha, nice idea @haslinger 🎉 Looks perfect on code side!
I'll try to test it on iPhone as well, but I think we're good to merge this commit already.

Awesome 🚀

**Comment by klappradla** [comment]
So I quickly sneaked in some time to look at it @haslinger. What's weird for me on the iPhone: I cannot scroll the page if I put my finger on the map (which at least for the size of my phone is the most convenient place). Is this different on Android? However, you can still scroll the page if you know how...
Kind of depends now what we think is less pain: figuring out where to point your finger or figuring out how to scroll without JUST scrolling the map 😉

**Comment by haslinger** [comment]
Yes, but that's not weird at all, see my last bullet above. :-) 
If you want the page to be dragged even when dragged on the map, you have to make leaflet bubble up/propagate the event again to the containing element, which it prevents by default. I didn't see an easy way to do this in the first place (in the docs), so we probably have to look into their code to make that happen again.

**Comment by klappradla** [comment]
Ah sorry @haslinger I though "single finger drag" did not refer to "scrolling". But sure, so same behavior on Android (as I would have expected).

**Pull request merged**
